# Stop and remove Docker containers
# vars:
#   - host_app_root
#   - env
---
- name: stop and remove {{ env }} Docker containers
  command: docker-compose down
  args:
    chdir: "{{ host_app_root }}"
