# Add deployment user
# vars:
#   - deployment_groups
#   - deployment_user
#   - ssh_pub_key
---
- name: Add {{ deployment_user }} user
  user:
    name: "{{ deployment_user }}"
    groups: "{{ deployment_groups }}"
    append: yes
    shell: /bin/bash

- name: Add authorized_key for {{ deployment_user }}
  include_role:
    name: os-add-ssh-access
  vars:
    user: "{{ deployment_user }}"
