# Add nginx available sites configurations
# vars:
#   - dhparam_key_size
#   - letsencrypt_root
---
- name: create directory {{ letsencrypt_root }}
  file:
    path: "{{ letsencrypt_root }}"
    state: directory

- name: generate new key exchange
  command: openssl dhparam -out {{ letsencrypt_root }}/dhparam.pem {{ dhparam_key_size }}
  args:
    creates: "{{ letsencrypt_root }}/dhparam.pem"
