# Add nginx available sites configurations
# vars:
#   - app_root
#   - hostnames
---
- name: create working directory
  file:
    path: "{{ app_root }}/.data/nginx/sites-available"
    state: directory

- name: make configuration files
  template:
    src: site.conf.j2
    dest: "{{ app_root }}/.data/nginx/sites-available/{{ item.split('.')[0] }}.conf"
  with_items: "{{ hostnames }}"
