# Add nginx available sites configurations
# vars:
#   - host_app_root
#   - hostnames
#   - nginx_site_template
#   - nginx_sites_available_path
#   - nginx_document_root (maintenance)
---
- name: create working directory
  file:
    path: "{{ nginx_sites_available_path }}"
    state: directory

- name: make configuration files
  template:
    src: "{{ nginx_site_template }}"
    dest: "{{ nginx_sites_available_path }}/{{ item.split('.')[0] }}.conf"
  with_items: "{{ hostnames }}"
