# Install letsencrypt SSL cert
# vars:
#   - cache_valid_time
#   - certbot_flags
#   - docker_compose
#   - host_app_root
#   - hostnames
#   - letsencrypt_config_dir
#   - letsencrypt_cron_hours
#   - letsencrypt_cron_minute
#   - letsencrypt_email
#   - letsencrypt_root
#   - web_service_name
---
- name: install letsencrypt CLI
  package:
    name: letsencrypt
    state: latest

- name: create directory {{ letsencrypt_config_dir }}
  file:
    path: "{{ letsencrypt_config_dir }}"
    state: directory

- name: create the configuration file
  template:
    src: cli.ini.j2
    dest: "{{ letsencrypt_config_dir }}/{{ item }}.ini"
  with_items: "{{ hostnames }}"

- name: get the certificates
  command: >
    letsencrypt certonly -c {{ letsencrypt_config_dir }}/{{ item }}.ini
    {{ certbot_flags }}
  args:
    creates: "{{ letsencrypt_root }}/live/{{ item }}"
  with_items: "{{ hostnames }}"

- name: install autorenew cron job
  cron:
    name: letsencrypt renew
    job: >
      letsencrypt renew --agree-tos >/var/tmp/letsencrypt.txt 2>&1
      && cd {{ host_app_root }}
      && {{ docker_compose }} restart {{ web_service_name }} >>/var/tmp/letsencrypt.txt 2>&1
    hour: "{{ letsencrypt_cron_hours }}"
    minute: "{{ letsencrypt_cron_minute }}"
