# Secure sshd
# vars:
#   - cache_valid_time
---
- name: disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
    state: present
  notify:
    - restart sshd

- name: install fail2ban
  package:
    name: fail2ban
    state: latest
