# Install docker-engine and docker-compose
# Add users to docker group
# vars:
#   - cache_valid_time
#   - docker_apt_key_id
#   - docker_apt_keyserver
#   - docker_repo
#   - docker_tools_deps_pkgs: apt packages that Docker needs
---
- name: install package dependencies
  package:
    name: "{{ docker_tools_deps_pkgs }}"
    state: latest

- name: logical volume setup
  command: dmsetup mknodes

- name: add docker apt key
  apt_key:
    keyserver: "{{ docker_apt_keyserver }}"
    id: "{{ docker_apt_key_id }}"

- name: add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"

- name: install docker-engine
  package:
    name: docker-engine
    state: latest

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: install docker-compose
  pip:
    name: docker-compose
    state: latest
